package com.gqt.corejava.exceptionHandling;
import java.util.Scanner;

class Operations1{
	void function1() {
		System.out.println("Inside funtion-1");
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter the first number");
		int n1 = sc.nextInt();
		System.out.println("Enter the second number");
		int
	}
}
public class Launch8 {

}
